[metadata]
name = oline-hri
version = attr: oline_hri.__version__
description = Offline personalized conversational robot software

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.10,<3.11
include_package_data = True
install_requires =
    numpy==2.2.6
    onnxruntime==1.23.2
    tokenizers==0.23.2

[options.packages.find]
where = src

[options.package_data]
oline_hri =
    default_config.json
    fictional_seven_day_v1.json
    fictional_seven_day_v1_1.json
    dependency_classifier_v1.json

[options.entry_points]
console_scripts =
    oline-hri = oline_hri.cli:main
